# Generated by Django 4.0.2 on 2022-02-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='slug',
            new_name='space_slug',
        ),
    ]
